# Generated by Django 4.2.3 on 2023-09-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
