# Generated by Django 4.2.3 on 2023-09-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0009_alter_userprofile_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phonenumber',
        ),
    ]
