# Generated by Django 4.2.3 on 2023-09-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0010_remove_userprofile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='default.webp', upload_to='profile_photos/'),
        ),
    ]
