# Generated by Django 4.2.3 on 2023-09-23 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vapp', '0017_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default='0', related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
