# Generated by Django 4.2.3 on 2023-09-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0020_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
