# Generated by Django 4.2.3 on 2023-09-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0026_comment_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
    ]
