# Generated by Django 4.2.3 on 2023-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0027_remove_comment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
