# Generated by Django 4.2.3 on 2023-09-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0028_comment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, default='default.webp', null=True, upload_to=''),
        ),
    ]
